# Generated by Django 3.0.6 on 2020-05-31 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlsoBought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'also_bought_items',
            },
        ),
        migrations.CreateModel(
            name='AlsoViewed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'also_viewed_items',
            },
        ),
        migrations.CreateModel(
            name='FourthCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'fourth_categories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('detail', models.TextField(null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=3, default=1, max_digits=4)),
                ('benefits', models.CharField(max_length=300)),
                ('also_bought', models.ManyToManyField(related_name='_item_also_bought_+', through='item.AlsoBought', to='item.Item')),
                ('also_viewed', models.ManyToManyField(related_name='_item_also_viewed_+', through='item.AlsoViewed', to='item.Item')),
                ('fourth_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.FourthCategory')),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'labels',
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'main_categories',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sub_categories',
            },
        ),
        migrations.CreateModel(
            name='ThirdCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'third_categories',
            },
        ),
        migrations.CreateModel(
            name='OptionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='item.Item')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Item')),
            ],
            options={
                'db_table': 'optional_items',
            },
        ),
        migrations.CreateModel(
            name='ItemLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Item')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Label')),
            ],
            options={
                'db_table': 'item_labels',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='labels',
            field=models.ManyToManyField(through='item.ItemLabel', to='item.Label'),
        ),
        migrations.AddField(
            model_name='item',
            name='main_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.MainCategory'),
        ),
        migrations.AddField(
            model_name='item',
            name='options',
            field=models.ManyToManyField(related_name='_item_options_+', through='item.OptionItem', to='item.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.SubCategory'),
        ),
        migrations.AddField(
            model_name='item',
            name='third_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.ThirdCategory'),
        ),
        migrations.AddField(
            model_name='alsoviewed',
            name='current',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='item.Item'),
        ),
        migrations.AddField(
            model_name='alsoviewed',
            name='viewed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Item'),
        ),
        migrations.AddField(
            model_name='alsobought',
            name='bought',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Item'),
        ),
        migrations.AddField(
            model_name='alsobought',
            name='current',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='item.Item'),
        ),
    ]
