# Generated by Django 3.0.6 on 2020-05-31 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_url', models.URLField(max_length=3000)),
                ('front_url', models.URLField(max_length=3000)),
                ('hover_url', models.URLField(max_length=3000)),
            ],
            options={
                'db_table': 'item_images',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='images',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.ItemImage'),
        ),
    ]
