# Generated by Django 3.0.6 on 2020-05-31 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'store_types',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=300)),
                ('contact', models.CharField(max_length=45)),
                ('opening_hours', models.CharField(max_length=200)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.StoreType')),
            ],
            options={
                'db_table': 'stores',
            },
        ),
    ]
