# Generated by Django 3.0.6 on 2020-05-31 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('discount', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('min_order', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'cart_coupons',
            },
        ),
        migrations.CreateModel(
            name='MobileCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=200, unique=True)),
                ('expiry_date', models.DateField()),
            ],
            options={
                'db_table': 'mobile_coupons',
            },
        ),
        migrations.CreateModel(
            name='UnregisteredUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=50)),
                ('orderer_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('recipient_address', models.CharField(max_length=200)),
                ('orderer_address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'unregistered_users',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('service_provider', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=2000)),
                ('points_sum', models.PositiveIntegerField(default=0)),
                ('privacy_3rd_party', models.BooleanField(default=False)),
                ('privacy_foreign', models.BooleanField(default=False)),
                ('point_message', models.BooleanField(default=False)),
                ('web_message', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('sum_paid', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'user_groups',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'wishlists',
            },
        ),
        migrations.CreateModel(
            name='UserMobileCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.MobileCoupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'user_mobile_coupons',
            },
        ),
        migrations.CreateModel(
            name='UserCartCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.CartCoupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'user_cart_coupons',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='cart_coupons',
            field=models.ManyToManyField(through='user.UserCartCoupon', to='user.CartCoupon'),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.UserGroup'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_coupons',
            field=models.ManyToManyField(through='user.UserMobileCoupon', to='user.MobileCoupon'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', models.CharField(max_length=50)),
                ('recipient_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('landline', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User')),
            ],
            options={
                'db_table': 'my_addresses',
            },
        ),
    ]
