# Generated by Django 3.0.6 on 2020-05-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20200531_0943'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wish_items',
            field=models.ManyToManyField(related_name='wishlisted_users', through='user.Wishlist', to='item.Item'),
        ),
    ]
