# Generated by Django 3.0.6 on 2020-06-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_wish_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartcoupon',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='cartcoupon',
            name='start_date',
        ),
        migrations.AddField(
            model_name='usercartcoupon',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='usercartcoupon',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
